### ISSUE TITLE
Display issue in Notifications

### ISSUE THREAD

**Issue by donotos** [pierobot/mangapie#220]
Hi.
When there is a lot of chapter for the same serie the selection is not displayed properly.

<img width="1142" alt="Capture d’écran 2020-06-24 à 20 20 24" src="https://user-images.githubusercontent.com/37663674/85611655-72587b00-b658-11ea-89a5-b83a36eb0b6a.png">

**Comment by kurim** [comment]
Now the issue has slightly change....
![image](https://user-images.githubusercontent.com/1880220/113928970-c1d6f480-97ef-11eb-827a-296c35e0b97f.png)

![image](https://user-images.githubusercontent.com/1880220/113928959-bedc0400-97ef-11eb-8917-1da5eb358a97.png)
